packages:
  - apps/web
  - packages/site-components
  - packages/web/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  lmdb: false
  msgpackr-extract: false

overrides:
  '@hono/node-server': 2.0.10
