"""Versioned structured-analysis contracts and deterministic normalization helpers."""

from platform_schemas.analysis import (
    ANALYSIS_SCHEMA_VERSION,
    AccessibilityObservation,
    AnalysisConfidence,
    AnalysisProvenance,
    ColorTokens,
    ComponentName,
    ComponentPattern,
    CopyPurpose,
    DesignTokens,
    FontCategory,
    PageProfile,
    PageType,
    ResponsiveBehavior,
    SectionPattern,
    SectionType,
    SpacingTokens,
    StyleTag,
    TypographyTokens,
    WebsiteProfile,
)
from platform_schemas.conversion import design_tokens_from_style_summary
from platform_schemas.migrations import migrate_website_profile, register_website_profile_migration

__all__ = [
    "ANALYSIS_SCHEMA_VERSION",
    "AccessibilityObservation",
    "AnalysisConfidence",
    "AnalysisProvenance",
    "ColorTokens",
    "ComponentName",
    "ComponentPattern",
    "CopyPurpose",
    "DesignTokens",
    "FontCategory",
    "PageProfile",
    "PageType",
    "ResponsiveBehavior",
    "SectionPattern",
    "SectionType",
    "SpacingTokens",
    "StyleTag",
    "TypographyTokens",
    "WebsiteProfile",
    "design_tokens_from_style_summary",
    "migrate_website_profile",
    "register_website_profile_migration",
]
