import { defineConfig } from '@hey-api/openapi-ts';

export const generatorConfig = {
  input: './openapi.json',
  output: {
    path: './src/generated',
    clean: true,
    header: [
      '// @ts-nocheck -- generated Angular runtime is validated by regeneration and consumer tests',
      '// This file is auto-generated by @hey-api/openapi-ts. Do not edit manually.',
    ],
  },
  plugins: [
    '@hey-api/client-angular',
    '@hey-api/typescript',
    {
      name: '@hey-api/sdk',
      operations: { strategy: 'byTags' },
    },
  ],
};

export default defineConfig(generatorConfig);
